### ISSUE TITLE
deprecated EAD elements in EAD3

### ISSUE THREAD

**Issue by MomoMoses** [johnjung/bmrcportal#38] opened 2021-10-07 17:05 UTC
We don't need to worry about these too much, as they weren't oft-used in any case:
`<extptr>`, `<extref>`, `<linkgrp>`

If there is code addressing or styling/transforming these tags, unless needed, comment out code addressing the use and display of these tags. Especially if this code is causing any anomalies in display or other function.

**Comment by johnjung** [comment] 2021-10-11 16:08
Right now, the transform tries to turn extptr and extref elements into HTML links, and it turns linkgrp elements into HTML unordered lists. Would you prefer that, if those elements appear in the EAD, nothing appears in the HTML? Or would you prefer that if those elements appear that plain text is output to HTML instead?

**Comment by MomoMoses** [comment] 2021-10-11 16:37
If you grep the database as it exists right now, do these elements appear? I don't see them in the NAFAN dataset at all. If they don't appear, it does no harm, but no good either. Since it's done, though, I would leave it as you have it--those transforms are logical.

**Comment by johnjung** [comment] 2021-10-15 17:34
The original issue here is now resolved, and yesterday's comment is a duplicate of https://github.com/johnjung/bmrcportal/issues/52. I'm going to close this issue out and finish resolving it over there.

**Closed by johnjung** 2021-10-15 17:34 UTC
