### ISSUE TITLE
descriptive summary headings

### ISSUE THREAD

**Issue by MomoMoses** [johnjung/bmrcportal#24] opened 2021-10-05 17:17 UTC
The Aaron H. Payne papers from UIC is the example. [https://bmrcportal-test.lib.uchicago.edu/view/?id=BMRC.UIC.PAYNE.xml](url)
Basic metadata includes Title, Identifier, Repository, Language, Size, Dates, and creator (sic - should be capitalized for consistency). Headings appear above metadata values, which are slightly indented. 

ISSUE: visibility and contrast -- 1. should the headings be in a different color, as are the capitalized section headings? 2. should the heading and data value be side by side vs. vertically placed? (space saver)

**Comment by johnjung** [comment] 2021-10-05 20:07
I'm tagging this one "design". I'm using HTML definition lists (the dl element) to mark these up- we should be able to restyle them in CSS. If I should mark these up a different way just let me know.

**Comment by MomoMoses** [comment] 2021-10-05 20:28
I don't know if these should be marked up differently - if it's easy to restyle in CSS though we should be good to go. that would be a Kathy call.

**Comment by johnjung** [comment] 2021-11-02 15:53
Re-reading this, this issue appears to be a duplicate of https://github.com/johnjung/bmrcportal/issues/49, which was just closed. I'm going to close this issue out too, but if you need to re-open it please feel free.

**Comment by MomoMoses** [comment] 2021-11-02 21:23
Though the italic styling is in the Mockup, I don't know if it's the choice of font or font size or the large screen or what, but I preferred the previous plain or bold (?) black type with a colon, then the data value. I think italics with this font are a little harder to read. Accessibility?

It's Ok for the selected facets since you've already read them. :)

**Comment by johnjung** [comment] 2021-11-05 19:55
This is now updated in https://github.com/johnjung/bmrcportal/commit/09edf269eb1b55e1260bfd7bb9d543581bad658f and live on the server. I removed the italics but didn't switch to bold- I think bold text here would change the hierarchy of the page pretty substantially compared to the mockup, and if there are still issues here I'd like to explore some other ways to solve them. Please review this and let me know what you think, if it looks good we can close this issue out.

**Comment by MomoMoses** [comment] 2021-11-05 22:07
Ok don’t get aggravated, but this does not look good. Let’s go back to italics and move on.🥸

**Comment by johnjung** [comment] 2021-11-08 18:45
It's easy enough to switch it back. This is now done in https://github.com/johnjung/bmrcportal/commit/0b321723ab786aef17637a9e5d89fcf5a074a34b, and live on the server. 

I'll close this issue out, but I'll tag it as "enhancement" so we can return to it later if you'd like.

**Closed by johnjung** 2021-11-08 18:45 UTC
Labels: enhancement, design
