### ISSUE TITLE
review color of links - blue

### ISSUE THREAD

**Issue by MomoMoses** [johnjung/bmrcportal#85] opened 2021-12-01 16:48 UTC
I can't remember if this blue was a holdover from earlier versions or if it was actually part of an intentional color palette. Some have observed that perhaps it's not the best color in the context of the overall color palette. I like the highlighted/selected link color but I'm also not sure about the unselected/available links on the pages.

Let's gather all the colors used into a style/palette document so we can review it as a whole.
#design

**Comment by johnjung** [comment] 2021-12-01 19:27
This appears to be a duplicate of https://github.com/johnjung/bmrcportal/issues/21- I'm going to close this issue out, but if you'd like to revisit the color of links let's do it on that issue so we can keep all of our notes together. 

Because the goal in phase two is to integrate the portal into bmrc.lib, link colors across the two sites will match. Because the timeline for doing that integration is tight, re-designing link colors from scratch is out of scope for phase two. However, if you have specific concerns about the link color please let me know. In this case it's also helpful for me to know which stakeholder raised this concern- if you'd like to talk about that offline please just let me know.

**Closed by johnjung** 2021-12-01 19:27 UTC

**Comment by MomoMoses** [comment] 2021-12-01 21:13
a board and working group member; also active with chicago collections... but not putting that forth as any kind of throwing their weight around -- just a personal response. Which I echo, actually. The blue is a bit off the palette to my mind as well.
